import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { usePersistentState } from "@tinqjs/tinjs-react-state";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PersistentStateExample />
    </div>
  );
}

function PersistentStateExample() {
  // const [tmpState, setTmpState] = useState("initial state");
  const [tmpState, setTmpState] = usePersistentState("persistent_example1", {
    initialValue: "initial value",
  });

  return (
    <div
      style={{
        marginTop: "2rem",
        display: "flex",
        justifyContent: "flex-start",
        alignItems: "center",
        gap: "2rem",
      }}
    >
      {/* <div>
        <button>Update</button>
      </div> */}
      <div>
        <input type="text" onChange={(e) => setTmpState(e.target.value)} />
      </div>
      <div>data : {tmpState}</div>
    </div>
  );
}
